[package]
name = "bridged_burn"
version = "0.1.0"
description = "Token exchange bridging mechanism"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "bridged_burn"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
solana-program = "2.1.1"
borsh = "0.10.3"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
solana-program-test = "2.1.1"
solana-sdk = "2.1.1"
spl-token = "7.0.0"
